name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install faker package
        run: |
          pip install faker

      - name: Run generate.py
        run: python generate.py

      - name: Run csvtojson.py
        run: python csvtojson.py

      - name: Copy files to dist
        run: |
          mkdir dist
          cp index.html dist/index.html
          cp script.js dist/script.js
          cp data.json dist/data.json

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
